// Generated declarations for OpTable specializations
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<Add>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<Sub>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<Mul>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<Div>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<Mod>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<Eq>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<Ne>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<Gt>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<Ge>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<Lt>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<Le>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<BitAnd>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<BitOr>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<BitXor>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<ShiftLeft>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<ShiftRight>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<LogicalAnd>::table;
template<> const std::array<std::array<BinaryOpFunc, TypeTagCount>, TypeTagCount> OpTable<LogicalOr>::table;
